# Generated by Django 5.0 on 2023-12-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='тема')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='описание')),
                ('status', models.CharField(choices=[('c', 'Created'), ('r', 'Running'), ('p', 'Paused'), ('f', 'Completed')], default='c', verbose_name='статус')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='день недели')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='день месяца')),
                ('periodic', models.CharField(choices=[('s', 'Single'), ('d', 'Daily'), ('w', 'Weekly'), ('m', 'Monthly')], max_length=1, verbose_name='периодичность')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
                ('time', models.TimeField(verbose_name='время начала')),
                ('is_active', models.BooleanField(default=True, verbose_name='активация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_last_attempt', models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')),
                ('status_of_last_attempt', models.BooleanField(default=False, verbose_name='cтатус последний попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.schedule', verbose_name='расписание')),
            ],
            options={
                'verbose_name': 'Mailing log',
                'ordering': ('-date_of_last_attempt',),
            },
        ),
    ]
