# Generated by Django 5.0 on 2023-12-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'ordering': ('-date_of_last_attempt',), 'verbose_name': 'Логи рассылки', 'verbose_name_plural': 'Логи рассылок'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'расписание', 'verbose_name_plural': 'расписания'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность'),
        ),
    ]
