# Generated by Django 5.0 on 2024-01-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='users',
            field=models.ManyToManyField(blank=True, to='mailing.user', verbose_name='Пользователи'),
        ),
    ]
