# Generated by Django 5.0 on 2024-01-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_schedule_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='время начала'),
        ),
    ]
