# Generated by Django 5.0 on 2024-01-14 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_message_subject_alter_message_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 14, 22, 16, 26, 545149), verbose_name='время начала'),
        ),
    ]
