# Generated by Django 5.0 on 2024-01-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_schedule_time_alter_schedule_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('r', 'Running'), ('p', 'Paused'), ('e', 'Failed'), ('f', 'Completed')], default='c', verbose_name='статус'),
        ),
    ]
