# Generated by Django 5.0 on 2024-02-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_rename_user_client_rename_users_schedule_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('r', 'Running'), ('p', 'Paused'), ('e', 'Failed'), ('f', 'Completed')], default='c', max_length=1, verbose_name='статус'),
        ),
    ]
