# Generated by Django 4.2.7 on 2024-02-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_message_owner_schedule_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
    ]
